### PR TITLE
Added the EnableNewOutlook key to the Microsoft Outlook manifest

### PR DESCRIPTION
**Pull request by timnottom**
Saw a tweet from William Smith and Jeffrey Kalvass that this key was added. Haven't found any offical posts form Microsoft so I've added the link to the tweet to the pfm_documentation_url. [link to tweet](https://twitter.com/jeffreykalvass/status/1296500175700205575).

Hope the description is ok, english isn't my first language.

First time trying to attribute by doing a pull request. Please let me know if and what I could have done better.

### CODE REVIEW

**Comment by timnottom** [comment]
Thanks @apizz! I didn't know it worked like that with the `pfm_last_modified` and `pfm_version`. Is this something that you in your role on this project do or can I (as the "forker") do that in the future?

And I noticed that you removed the `pfm_description_reference`. I didn't really understand what it was for, but I copied it from another key.

**Comment by apizz** [comment]
The description is really the user-friendly one while the reference is whatever is listed in the documentation. The key isn't really used by the app unless the description isn't present.

**Comment by apizz** [comment]
If you leave the last modified or version unchanged I'll handle it but if you wanted to save me a step you can change them yourself.

**Comment by timnottom** [comment]
> If you leave the last modified or version unchanged I'll handle it but if you wanted to save me a step you can change them yourself.

Thanks! Good to know!

**Pull request merged**
