### PR TITLE
Added AutomaticallyInstallMacOSUpdates

### PR DESCRIPTION
**Pull request by wegotoeleven**
Added AutomaticallyInstallMacOSUpdates key. This disables the following:

screenshot 2019-01-04 at 14 16 29

### CODE REVIEW

**Comment by apizz** [comment]
@wegotoeleven Given that this preference was added in Mojave, you'll need to add `pfm_macos_min` key to the preference

**Comment by wegotoeleven** [comment]
@apizz - added. Thanks for the heads up :)

**Comment by apizz** [comment]
@wegotoeleven missed one thing.  Would you mind bumping the `pfm_version`?  As soon as that's done I'll get this merged.

**Comment by wegotoeleven** [comment]
Done, version bumped. Should this be done for all profile manifests, just for my information?

Merci :)

**Comment by apizz** [comment]
This was updated in https://github.com/erikberglund/ProfileManifests/pull/63

**Pull request merged**
